# Generated by Django 3.0.8 on 2020-08-10 10:52

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('authors', django_mysql.models.ListCharField(models.CharField(max_length=50), max_length=550, size=10)),
                ('published_date', models.CharField(max_length=10)),
                ('categories', django_mysql.models.ListCharField(models.CharField(max_length=50), default=None, max_length=550, null=True, size=10)),
                ('average_rating', models.IntegerField(default=None, null=True)),
                ('ratings_count', models.IntegerField(default=None, null=True)),
                ('thumbnail', models.URLField(default=None, null=True)),
                ('year', models.IntegerField()),
            ],
            options={
                'ordering': ['year'],
            },
        ),
    ]
